project:
  type: website
  output-dir: docs
  preview:
    port: 4200
  render: 
    - "*.qmd"
    - "!ignored.qmd"
    - "!ignored-dir/"

website:
  title: "Mehmet Fatih Kara"
  site-url: "https://www.mfkara.net/"
  repo-url: "https://github.com/karamehmetfatih/karamehmetfatih.github.io"
  favicon: img/favicon.png
  description: "A sample blog"
  back-to-top-navigation: true
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/karamehmetfatih/karamehmetfatih.github.io
          - text: Report an Issue
            href: https://github.com/karamehmetfatih/karamehmetfatih.github.io/issues
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
        icon: github
      - href: posts/index.qmd
        text: "Blog"
      - href: papers/index.qmd
        text: Papers
      - href: about.qmd
        text: About
  search: 
    location: navbar
    type: textbox
  page-footer: 
    background: light
    center: © 2026  &middot; Made with {{< fa brands r-project >}} and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)
    right: 
      - icon: bluesky
        href: https://bsky.app/profile/mfkara.net
      - icon: linkedin
        href: www.linkedin.com/in/m-f-kara
      - text: "{{< fa envelope >}}"
        href: mailto:info@mfkara.net

format:
  html:
    theme: sandstone
    mainfont: arial
    monofont: courier new 
    css: styles.css
    toc: true



